export default {
  SERVICE_FETCH_TASKS: 'SERVICE_FETCH_TASKS',
  SERVICE_REMOVE_TASK: 'SERVICE_REMOVE_TASK',
  SERVICE_UPDATE_TASK: 'SERVICE_UPDATE_TASK',
  SERVICE_CREATE_TASK: 'SERVICE_CREATE_TASK',
  SERVICE_LOGIN: 'SERVICE_LOGIN',
  SERVICE_LOGOUT: 'SERVICE_LOGOUT',
  SET_TASKS: 'SET_TASKS',
  LOGIN: 'LOGIN',
  LOG_OUT: 'LOG_OUT',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  SERVICE_FETCH_TASKS_FAILED: 'SERVICE_FETCH_TASKS_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  CREATE_TASK_FAILED: 'CREATE_TASK_FAILED'
};